use ExtUtils::MakeMaker;
# See lib/ExtUtils/MakeMaker.pm for details of how to influence
# the contents of the Makefile that is written.
WriteMakefile(
    'NAME'		=> 'Dev-Bollocks',
    'VERSION_FROM'	=> 'lib/Dev/Bollocks.pm', # finds $VERSION
    'PREREQ_PM'		=> { 
			Math::String => 1.16
			   },
    'LIBS'		=> [''], # e.g., '-lm'
    'DEFINE'		=> '', # e.g., '-DHAVE_SOMETHING'
    'INC'		=> '', # e.g., '-I/usr/include/other'
);
